version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna
      MYSQL_PASSWORD: lavagnapass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  lavagna-for-mysql:
    image: lavagna-for-mysql
    restart: always
    depends_on:
      - mysql
    environment:
      DB_DIALECT: MYSQL
      DB_URL: jdbc:mysql://mysql:3306/lavagna?autoReconnect=true&useSSL=false
      DB_USER: lavagna
      DB_PASS: lavagnapass
      SPRING_PROFILE: dev
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp:/usr/share/nginx/html/webapp
      - ./README.md:/usr/share/nginx/html/README.md
    networks:
      - frontend
    depends_on:
      - lavagna-for-mysql

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql-data:
